apiVersion: skaffold/v2beta14
kind: Config
metadata:
  name: spring-boot-kubernetes-demo
build:
  artifacts:
    - image: docker.io/sivaprasadreddy/vote-service
      context: ./vote-service
      buildpacks:
        builder: paketobuildpacks/builder:base
    - image: docker.io/sivaprasadreddy/bookmark-service
      context: ./bookmark-service
      buildpacks:
        builder: paketobuildpacks/builder:base
    - image: docker.io/sivaprasadreddy/api-gateway
      context: ./api-gateway
      buildpacks:
        builder: paketobuildpacks/builder:base
    - image: docker.io/sivaprasadreddy/bookmarks-ui
      context: ./bookmarks-ui
      buildpacks:
        builder: paketobuildpacks/builder:base

deploy:
  kubectl:
    manifests:
      - k8s/1-config.yaml
      - k8s/2-bookmarks-postgresdb.yaml
      - k8s/3-votes-postgresdb.yaml
      - k8s/4-bookmark-service-app.yaml
      - k8s/5-vote-service-app.yaml
      - k8s/6-api-gateway.yaml
      - k8s/7-bookmarks-ui-app.yaml
      - k8s/8-ingress.yaml
