apiVersion: skaffold/v2beta14
kind: Config
metadata:
  name: spring-boot-kubernetes-demo
build:
  artifacts:
    - image: docker.io/sivaprasadreddy/url-metadata-service
      context: ./url-metadata-service
      jib: {}
      #buildpacks:
      #  builder: paketobuildpacks/builder:base
    - image: docker.io/sivaprasadreddy/bookmarks-service
      context: ./bookmarks-service
      jib: {}
      #buildpacks:
      #  builder: paketobuildpacks/builder:base
    - image: docker.io/sivaprasadreddy/api-gateway
      context: ./api-gateway
      jib: {}
      #buildpacks:
      #  builder: paketobuildpacks/builder:base
    - image: docker.io/sivaprasadreddy/bookmarks-ui
      context: ./bookmarks-ui
      jib: {}
      #buildpacks:
      #  builder: paketobuildpacks/builder:base

deploy:
  kubectl:
    manifests:
      - k8s/1-config.yaml
      - k8s/2-bookmarks-postgresdb.yaml
      - k8s/4-url-metadata-service-app.yaml
      - k8s/5-bookmarks-service-app.yaml
      - k8s/6-api-gateway.yaml
      - k8s/7-bookmarks-ui-app.yaml
      - k8s/8-ingress.yaml
