spring:
  cloud:
    gateway:
      routes:
        - id: bookmarks-service
          uri: http://bookmarks-service:8081
          predicates:
            - Path=/bookmarks/**
          filters:
            - StripPrefix=1
        - id: url-metadata-service
          uri: http://url-metadata-service:8082
          predicates:
            - Path=/url-metadata/**
          filters:
            - StripPrefix=1
