server:
  port: 9090
  shutdown: graceful

spring:
  application.name: api-gateway
  zipkin:
    base-url: http://localhost:9411/
    enabled: false
  sleuth.sampler.probability: 1
  cloud.gateway.routes:
        - id: bookmarks-service
          uri: http://localhost:8081
          predicates:
            - Path=/bookmarks/**
          filters:
            - RewritePath=/bookmarks/(?<path>.*), /$\{path}
        - id: votes-service
          uri: http://localhost:8082
          predicates:
            - Path=/votes/**
          filters:
            - RewritePath=/votes/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
      discovery:
        locator:
          enabled: true
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
