server:
  port: 9090
  shutdown: graceful

spring:
  application.name: api-gateway
  zipkin:
    base-url: http://localhost:9411/
    enabled: false
  sleuth.sampler.probability: 1
  cloud.gateway.routes:
        - id: bookmarks_route
          uri: http://localhost:8081
          predicates:
            - Path=/bookmarkssvc/**
          filters:
            - StripPrefix=1
        - id: votes_route
          uri: http://localhost:8082
          predicates:
            - Path=/votessvc/**
          filters:
            - StripPrefix=1
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
