spring:
  cloud:
    gateway:
      routes:
        - id: bookmarks-service
          uri: http://bookmarks-service:8081
          predicates:
            - Path=/bookmarks/**
          filters:
            - RewritePath=/bookmarks/(?<path>.*), /$\{path}
        - id: url-metadata-service
          uri: http://url-metadata-service:8082
          predicates:
            - Path=/url-metadata/**
          filters:
            - RewritePath=/url-metadata/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
