---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookmark-service-postgres-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: bookmark-service-postgres-svc
spec:
  selector:
    app: bookmark-service-postgres-pod
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmark-service-postgres-deployment
spec:
  selector:
    matchLabels:
      app: bookmark-service-postgres-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bookmark-service-postgres-pod
    spec:
      containers:
        - name: postgres
          image: "postgres:12.3"
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: bookmark-service-secrets
                  key: postgres_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bookmark-service-secrets
                  key: postgres_password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: bookmark-service-configmap
                  key: postgres_database
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: bookmark-service-postgres-pv-claim
