apiVersion: v1
kind: Service
metadata:
  name: bookmark-service-svc
spec:
  type: NodePort
  selector:
    app: bookmark-service-pod
  ports:
    - name: app-port-mapping
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmark-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookmark-service-pod
  template:
    metadata:
      labels:
        app: bookmark-service-pod
    spec:
      containers:
        - name: bookmark-service
          image: sivaprasadreddy/bookmark-service:0.0.1
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: APPLICATION_VOTE_SERVICE_URL
              value: http://vote-service-svc:8082
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: bookmark-service-configmap
                  key: postgres_host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: bookmark-service-configmap
                  key: postgres_port
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: bookmark-service-configmap
                  key: postgres_database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bookmark-service-secrets
                  key: postgres_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bookmark-service-secrets
                  key: postgres_password
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]
          volumeMounts:
            - name: config-volume
              mountPath: /workspace/config
      volumes:
        - name: config-volume
          configMap:
            name: bookmark-service-configmap
