apiVersion: v1
kind: Service
metadata:
  name: vote-service-svc
spec:
  type: NodePort
  selector:
    app: vote-service-pod
  ports:
    - name: app-port-mapping
      protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-service-pod
  template:
    metadata:
      labels:
        app: vote-service-pod
    spec:
      containers:
        - name: vote-service
          image: sivaprasadreddy/vote-service:0.0.1
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: vote-service-configmap
                  key: postgres_host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: vote-service-configmap
                  key: postgres_port
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: vote-service-configmap
                  key: postgres_database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: vote-service-secrets
                  key: postgres_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vote-service-secrets
                  key: postgres_password
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]
          volumeMounts:
            - name: config-volume
              mountPath: /workspace/config
      volumes:
        - name: config-volume
          configMap:
            name: vote-service-configmap
