version: '3.5'
services:
  prometheus:
    image: prom/prometheus:v2.24.0
    container_name: monitoring-prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:7.3.6
    container_name: monitoring-grafana
    ports:
    - 3000:3000
    volumes:
    - grafana_data:/var/lib/grafana
    - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=admin
    - GF_SECURITY_ADMIN_USER=admin
    - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
    - prometheus

volumes:
  prometheus_data: {}
  grafana_data: {}
  esdata1:
    driver: local

