server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: bookmarks-ui
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
  cloud:
    gateway:
      routes:
        - id: bookmarks_route
          uri: http://localhost:8081
          predicates:
            - Path=/bookmarkssvc/**
          filters:
            - StripPrefix=1
        - id: votes_route
          uri: http://localhost:8082
          predicates:
            - Path=/votessvc/**
          filters:
            - StripPrefix=1
management:
  endpoints:
    web:
      exposure:
        include: '*'
